---
name: Net-FriendFeed
version: 0.99
author:
  - 'Alex Kapranoff <kappa@cpan.org>'
abstract: Perl interface to FriendFeed.com API
license: gpl
resources:
  license: http://opensource.org/licenses/gpl-license.php
build_requires:
  Test::Deep: 0
  Test::MockObject: 0
  Test::NoWarnings: 0
requires:
  Class::Accessor: 0
  Encode: 0
  HTTP::Request::Common: 0
  JSON: 2
  LWP::UserAgent: 0
  URI: 0
  perl: 5.008
configure_requires:
  Module::Build: 0.35
provides:
  Net::FriendFeed:
    file: lib/Net/FriendFeed.pm
    version: 0.99
  Test::MockHTTP:
    file: lib/Test/MockHTTP.pm
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
